spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/douban
    username: root
    password: 123456
  jpa:
    hibernate:
    show-sql: true
  application:
    name: Backend
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus